### PR TITLE
Use CDP's ensure-docker

### PR DESCRIPTION
**Pull request by jmcs**
Use standardized way to install docker in CDP builds.

### CODE REVIEW

**Comment by lotharschulz** [comment]
👍

**Comment by hjacobs** [comment]
Build fails:

```
 + docker build -t 'pierone.stups.zalan.do/bus/pierone.stups.zalan.do/bus/lizzy:cdp#{CDP_TARGET_BRANCH_COUNTER}' .
2017-06-27T06:40:16.107076344Z invalid argument "pierone.stups.zalan.do/bus/pierone.stups.zalan.do/bus/lizzy:cdp#{CDP_TARGET_BRANCH_COUNTER}" for t: Error parsing reference: "pierone.stups.zalan.do/bus/pierone.stups.zalan.do/bus/lizzy:cdp#{CDP_TARGET_BRANCH_COUNTER}" is not a valid repository/tag: invalid reference format
2017-06-27T06:40:16.107097383Z See 'docker build --help'.
```

**Comment by jmcs** [comment]
:+1:

**Comment by jmcs** [comment]
:+1:

**Comment by dryewo** [comment]
👍

**Pull request merged**
